version: "3"
services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
    - /root/deployments/nginx/default.conf:/etc/nginx/conf.d/default.conf
    - /root/deployments/nginx/ssl:/etc/nginx/ssl/
    ports:
    - 80:80
