version: '2'
services:
  jenkins:
    build: .
    image: jenkins-docker
    container_name: jenkins
    user: root
    volumes:
      - ~/Music/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5986:8080"